var build = require('./truffle.js');

var config = {
    url: "http://" + build.rpc.host + ":" + build.rpc.port,
    defaultAccount: web3.eth.accounts[0],
    contractAddress: Volatility.deployed().contract.address,
    contractABI: Volatility.deployed().abi
}

console.log("// Auto generated by info.js, do not modify.\n\nexport default " + JSON.stringify(config))

process.exit()